sudo: required
language: generic 
services:
  - docker 

before_install:
  - docker build -t ammar1ammar1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ammar1ammar1/docker-react npm run test 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  
  on:
    branch: master