sudo: required
language: generic 
services:
  - docker 

before_install:
  - docker build -t ammar1ammar1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ammar1ammar1/docker-react npm run test 

deploy:
  provider: pages
  skip_cleanup: true
  token: $gh-token
  local_dir: build
  on:
    branch: master